version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: '02:00'
    timezone: Europe/London
  open-pull-requests-limit: 10
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: '02:00'
    timezone: Europe/London
  open-pull-requests-limit: 10
