name: Docker Image CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Run Buildx
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
          DOCKER_BUILDKIT: 1
        run: |
          docker build --platform=local -o . git://github.com/docker/buildx
          mkdir -p ~/.docker/cli-plugins
          mv buildx ~/.docker/cli-plugins/docker-buildx
          docker buildx build \
            --tag ${GITHUB_REPOSITORY}:latest \
            --platform linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x \
            .

      - name: Docker login
        if: github.ref == 'refs/heads/master'
        env:
          docker_username: ${{ secrets.docker_username }}
          docker_password: ${{ secrets.docker_password }}
        run: docker login  -u $docker_username -p ${docker_password}

      - name: Tag
        run: docker tag ${GITHUB_REPOSITORY}:latest ${GITHUB_REPOSITORY}:${GITHUB_SHA}

      - name: Push latest
        if: github.ref == 'refs/heads/master'
        run: docker push ${GITHUB_REPOSITORY}:latest

      - name: Push sha
        if: github.ref == 'refs/heads/master'
        run: docker push ${GITHUB_REPOSITORY}:${GITHUB_SHA}
