name: Docker Image CI
on: [push]

jobs:
  build:
    uses: chrisns/.github/.github/workflows/dockerbuild.yml@main
    with:
      platforms: linux/arm64,linux/amd64
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
