name: "Security Scanning"
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  scan:
    name: Security Scan
    uses: chrisns/repo-config/.github/workflows/security-scan.yml@main
